FROM node:22-bookworm-slim AS base

WORKDIR /app
ENV NEXT_TELEMETRY_DISABLED=1

FROM base AS deps

COPY package.json package-lock.json ./
COPY apps/petCorner/package.json ./apps/petCorner/package.json
COPY apps/petpage/package.json ./apps/petpage/package.json

RUN npm ci

FROM base AS builder

ARG NEXT_PUBLIC_APP_URL
ARG NEXT_PUBLIC_FIREBASE_API_KEY
ARG NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN
ARG NEXT_PUBLIC_FIREBASE_PROJECT_ID
ARG NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET
ARG NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID
ARG NEXT_PUBLIC_FIREBASE_APP_ID
ARG NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID
ARG NEXT_PUBLIC_CLOUDFLARE_WORKER_URL
ARG NEXT_PUBLIC_COSMOS_SYNC_URL
ARG NEXT_PUBLIC_CHAT_WORKER_URL
ARG VITE_FIREBASE_API_KEY
ARG VITE_FIREBASE_AUTH_DOMAIN
ARG VITE_FIREBASE_PROJECT_ID
ARG VITE_FIREBASE_STORAGE_BUCKET
ARG VITE_FIREBASE_MESSAGING_SENDER_ID
ARG VITE_FIREBASE_APP_ID
ARG VITE_FIREBASE_MEASUREMENT_ID
ARG VITE_COSMOS_SYNC_URL
ARG VITE_CHAT_WORKER_URL

ENV NODE_ENV=production
ENV NEXT_PUBLIC_APP_URL=${NEXT_PUBLIC_APP_URL}
ENV NEXT_PUBLIC_FIREBASE_API_KEY=${NEXT_PUBLIC_FIREBASE_API_KEY}
ENV NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=${NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN}
ENV NEXT_PUBLIC_FIREBASE_PROJECT_ID=${NEXT_PUBLIC_FIREBASE_PROJECT_ID}
ENV NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=${NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET}
ENV NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=${NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID}
ENV NEXT_PUBLIC_FIREBASE_APP_ID=${NEXT_PUBLIC_FIREBASE_APP_ID}
ENV NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID=${NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID}
ENV NEXT_PUBLIC_CLOUDFLARE_WORKER_URL=${NEXT_PUBLIC_CLOUDFLARE_WORKER_URL}
ENV NEXT_PUBLIC_COSMOS_SYNC_URL=${NEXT_PUBLIC_COSMOS_SYNC_URL}
ENV NEXT_PUBLIC_CHAT_WORKER_URL=${NEXT_PUBLIC_CHAT_WORKER_URL}
ENV VITE_FIREBASE_API_KEY=${VITE_FIREBASE_API_KEY}
ENV VITE_FIREBASE_AUTH_DOMAIN=${VITE_FIREBASE_AUTH_DOMAIN}
ENV VITE_FIREBASE_PROJECT_ID=${VITE_FIREBASE_PROJECT_ID}
ENV VITE_FIREBASE_STORAGE_BUCKET=${VITE_FIREBASE_STORAGE_BUCKET}
ENV VITE_FIREBASE_MESSAGING_SENDER_ID=${VITE_FIREBASE_MESSAGING_SENDER_ID}
ENV VITE_FIREBASE_APP_ID=${VITE_FIREBASE_APP_ID}
ENV VITE_FIREBASE_MEASUREMENT_ID=${VITE_FIREBASE_MEASUREMENT_ID}
ENV VITE_COSMOS_SYNC_URL=${VITE_COSMOS_SYNC_URL}
ENV VITE_CHAT_WORKER_URL=${VITE_CHAT_WORKER_URL}

COPY --from=deps /app ./
COPY . .

RUN npm run build --workspace=petcorner
RUN npm run build --workspace=petpage
RUN npm prune --omit=dev

FROM base AS runner

ENV NODE_ENV=production
ENV HOSTNAME=0.0.0.0
ENV PORT=3000
ENV NEXT_TELEMETRY_DISABLED=1

RUN groupadd --system --gid 1001 nodejs \
  && useradd --system --uid 1001 --gid nodejs nextjs

COPY --from=builder --chown=nextjs:nodejs /app/package.json ./package.json
COPY --from=builder --chown=nextjs:nodejs /app/package-lock.json ./package-lock.json
COPY --from=builder --chown=nextjs:nodejs /app/node_modules ./node_modules
COPY --from=builder --chown=nextjs:nodejs /app/apps/petpage/package.json ./apps/petpage/package.json
COPY --from=builder --chown=nextjs:nodejs /app/apps/petpage/.next ./apps/petpage/.next
COPY --from=builder --chown=nextjs:nodejs /app/apps/petpage/public ./apps/petpage/public
COPY --from=builder --chown=nextjs:nodejs /app/apps/petpage/next.config.ts ./apps/petpage/next.config.ts
COPY --from=builder --chown=nextjs:nodejs /app/apps/petpage/scripts ./apps/petpage/scripts

USER nextjs
WORKDIR /app/apps/petpage

EXPOSE 3000

CMD ["node", "scripts/next-with-userland-punycode.cjs", "start"]
